code --install-extension akamud.vscode-theme-onedark
code --install-extension bungcip.better-toml
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension jakebathman.mysql-syntax
code --install-extension johnpapa.vscode-peacock
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension mermade.openapi-lint
code --install-extension miclo.sort-typescript-imports
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension philosowaffle.openapi-designer
code --install-extension pnp.polacode
code --install-extension rbbit.typescript-hero
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension shardulm94.trailing-spaces
code --install-extension Tyriar.sort-lines
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
